### ISSUE TITLE
Implement CODEOWNERS

### ISSUE THREAD

**Issue by NotMoni** [node-fetch/node-fetch#852] opened 2020-05-29 17:14 UTC
https://github.blog/2017-07-06-introducing-code-owners/

We have made great strides in Node-Fetch these few months but I feel that things have been moving very fast in this repo even with having every PR reviewed by 3 people before merging.

So I am introducing `CODEOWNERS`. 

So basically, we have a set of people that **have** to approve for Code Changes. Others can also approve like the maintainers, but i suggest we have 2 - 3 people approve the code. As for the 2 -3 people, I think it should be those in the @node-fetch/core for Code Changes. 

For other PR's that don't have code change, we can have both @node-fetch/core and @node-fetch/reviewers take a look at it. 

You might be thinking about why this might be needed.

**In the past week, we merged 27 PR's**

**Take a look in the spike of code deletions and additions**

**We had two releases and one was a fix.** 

So, we definitely need to slow things down ( **mainly merging** ) and take a look at reviewing code.
Reviewing code is as important as writing it. 

![image](https://user-images.githubusercontent.com/40552237/83286142-71454280-a1ad-11ea-9483-b09f63279aed.png)

![image](https://user-images.githubusercontent.com/40552237/83286546-13fdc100-a1ae-11ea-802b-357270d4470c.png)

![image](https://user-images.githubusercontent.com/40552237/83286223-89b55d00-a1ad-11ea-92b9-30ecb42f0d75.png)

#### **If we come to the conclusion of implementing this feature, I can get started on working on a PR.**

**Comment by JefferyHus** [comment] 2020-05-29 17:18
Totally true

**Comment by tinovyatkin** [comment] 2020-05-29 20:09
While I'm complete :+1: for CODEOWNERS I have a couple of comments regarding the rest of the issue motivation:

1. There is nothing wrong in a contribution surge for a project with a small team and without full-time authors - as it all _freetime_ contributions (somebody does that because have time between projects, somebody due to immediately need to fix a bug, and somebody because he is jobless and would like to contribute to the community in the meanwhile (me 🙋🏻‍♂️))). 

2. The problem with bugfix release was found by a team member in less than 2 hours and mitigated not only with the regression test (#838), but also with minimum review policy change.

3. I think no developers team should set "slow down" as an objective - if test suites are comprehensive, code review policy in place and contributions coming - that's great and should be appreciated, and not be seen like something suspicious.

**Comment by xxczaki** [comment] 2020-05-29 20:39
Introducing a more strict policy on merging PRs is a great idea. However, a couple of notes:

- the releases you mentioned were made before introducing the minimum review requirements;
- some of the PRs included in the amount were not related to code, but to things like Github Actions, documentation, issue/PR templates;
- the huge spike happened in March when we merge the `3.x` branch into master and  published the first beta versions, which contained many issues;

And just like @tinovyatkin said - with better tests, the new review policy, and now the CODEOWNERS file, we will be able to work on the `3.x` version relatively quickly without much risks involved.

**Comment by NotMoni** [comment] 2020-05-29 20:53
@tinovyatkin I agree with you but... one comment.

1.) I am not attacking you in any way, I also made tons of PRs and Issues during the time. I was reflecting and saying that **we** all should be a little more careful when merging. I am a student dev and for all I know, we are all in here together working on node-fetch. It is a tough time for everyone around the world and we are here working on node-fetch, which is great and we all appreciate you for helping to fix tons of issues.

**Comment by NotMoni** [comment] 2020-05-29 20:55
@xxczaki I agree with you on the comments above. The surge was not all code but other maintenance stuff in the repo.

**Comment by Richienb** [comment] 2020-05-30 04:33
We already require at least 3 PR reviewers. In my opinion, we already have enough safeguards.

**Comment by NotMoni** [comment] 2020-05-30 13:35
Are you sure? I think we should enable it, because what if those 3 reviews were from ppl that are not a node-fetch member. Anyone can review and approve code in Github, and it would count as a review. CODEOWNERS makes sure at least 1 or 2 people from the @node-fetch/core have taken a look at it.

**Comment by NotMoni** [comment] 2020-05-30 13:38
If anything, PR's might be not merged for an extra day or two.

**Comment by Richienb** [comment] 2020-05-30 13:39
@xxczaki @bitinn What's your opinion?

**Comment by xxczaki** [comment] 2020-05-31 10:01
@Richienb I feel like the current system works just fine. We might want to implement CODEOWNERS when some accidents start to happen, which is unlikely with 3 required reviews.

**Comment by tinovyatkin** [comment] 2020-05-31 11:45
> Anyone can review and approve code in Github, and it would count as a review. 

Only review from a members with write access are counting toward required reviews.

And PR merging are notoriously slow now.

**Comment by xxczaki** [comment] 2020-05-31 12:01
@tinovyatkin We can try and reduce the number of required reviews to 2 if you want. If it works well, we can leave it like so.

**Comment by Richienb** [comment] 2020-05-31 12:10
@tinovyatkin At the moment, I don't think any prs are being held back by a lack of reviewers. However, when we get to that point, I'll be happy to reduce the requirement.

**Comment by tinovyatkin** [comment] 2020-05-31 12:11
It’s not about what I want, but I think that for a project with existing 100% coverage 3 reviews is overkill and requires a lot of dedication from team members and a lot of patience from a contributor.

I mean, there is some PRs that are too boring to review, etc.

What @NotMoni is missing here is that CODEOWNERS primary function is not to require review from somebody (this is actually an option in setting), but to automatically _request_ review from a person mentioned there for a changed file. For example, I would love to be the codeowner for Headers and TypeScript files, because I’d basically rewritten them from the scratch recently. 
That said, I that the ideal settings will be codeowners + 2 required review.



That said, I

**Comment by Richienb** [comment] 2020-05-31 12:19
> but to automatically _request_ review from a person mentioned there for a changed file.

👍

**Comment by tinovyatkin** [comment] 2020-05-31 12:20
And anyway maintainers should not loss the common sense before merging - even when requirements by reviews are met - if there is an ongoing discussion in a PR or some request for change not attended - it’s no go for merge.

**Comment by NotMoni** [comment] 2020-05-31 14:15
Alright, then.
 I think everyone wants to use CODEOWNERS as a way to request a review from a person.
So put an 👍 if you agree and if we hit 5 👍 then we can implement it.

**Comment by bitinn** [comment] 2020-05-31 14:47
If the main issue is we are merging too fast, I think an alternative solution would be to add a label that indicate a PR needs more consensus / feedbacks, such that core members shouldn't merge too hastily.

In cases like:

- breaking changes;
- adding major features;
- build pipeline, package.json, export updates;

These PR have potential to cause issues for many users, so we should ensure reviews are being done properly and not just merge based on approval count.

It's not always possible to find the code owner as we are probably all doing this part-time.

Preferably reviewers should write some comments after reviewing, so that people in charge of merging is not left to wonder how in-depth the review was.

**Comment by tinovyatkin** [comment] 2020-05-31 14:51
@NotMoni just a note: not a meticulously implemented `CODEOWNERS` will do more pain than benefits:
1. It's better to not put a file into CODEOWNERS if we are not absolutely sure that there is an original author or person with deep knowledge in the area who is in the team.
2. It's better to not put as a codeowner a maintainer who may not have enough time for reviews
3. CODEOWNERS works best when project structure is as modulized as possible, for example, XO and `tsd` should be separated from `package.json` as, most probably, they should have different code owners. When test modularization will be finished then particular test should probably also have different code owners.

I mean, it's not a _copy a template_ work, if you up for it prepare to do good research first, so, we will not repeat the experience with PR templates.

**Comment by NotMoni** [comment] 2020-05-31 15:18
@tinovyatkin 😔Alright

**Comment by tinovyatkin** [comment] 2020-06-09 03:08
Is it just me or somebody else are feeling that 3 reviews basically stops the project movement? We’ve merged only minor documentation fixes since the requirement was introduced.

**Closed** 2020-06-09 13:09 UTC
Labels: help wanted, meta

**Comment by xxczaki** [comment] 2020-06-09 13:41
@tinovyatkin @node-fetch/core 

I changed the number of required PR reviews from 3 to 2, hopefully this will help.
