### ISSUE TITLE
method: GET does not send headers

### ISSUE THREAD

**Issue by bobber205** [node-fetch/node-fetch#676] opened 2019-09-19 20:32 UTC
Why is this? Some APIs required a Bearer token for get requests, like the Spotify API does, and afaik you cannot use fetch() with method: 'get' and send over headers?

What's the reasoning for this?

**Comment by gr2m** [comment] 2019-09-20 03:11
can you share your code? I use `node-fetch` a lot and never had problems with sending headers with any method

**Comment by bobber205** [comment] 2019-09-23 16:26
I was doing something like this

```
await fetch(accounts_token_url, { method: 'get', headers: {some_header_Varible} });
```

And this just worked first try:

```
await request.get({url: accounts_token_url, headers: {same_as_above_header})
```

**Comment by Richienb** [comment] 2019-10-04 03:52
@bobber205 I'm unable to recreate this issue. Are you able to create a unit test case for this?

**Comment by noushad-pp** [comment] 2019-10-14 14:43
I have the exact same experience as @bobber205 . I switched to request library and it worked.
```
 try {
      const url = new URL('http://my_api_url');
      url.search = queryObject;
      const data = await fetch(url, {
        method: "GET",
        headers: { "X-API-Authentication": process.env.PROXY_API_TOKEN },
        timeout: 5000,
      });
      const res = await data.clone().json();
      response.send(res);
    } catch (e) {
      console.error(e);
      return await returnMockData();
    }
```

I switched to same code expect
```
const data = await request.get({
        url,
        method: "GET",
        headers: { "X-API-Authentication": process.env.PROXY_API_TOKEN },
        timeout: 5000,
      });
```

and it works

**Comment by xxczaki** [comment] 2020-04-21 09:00
Closing, as we are unable to reproduce this. If this issue still occurs, please open a new issue with clear reproduction steps.

**Closed by xxczaki** 2020-04-21 09:00 UTC
Labels: awaiting-author-response
