### ISSUE TITLE
provide commonjs build

### ISSUE THREAD

**Issue by image72** [node-fetch/node-fetch#1235] opened 2021-08-05 12:26 UTC
**Example Code**

```sh
node -r node-fetch -i
```

**Expected behavior, if applicable**

please provide strict `commonjs` build, esmodules or webpack alternative cannot used everywhere.

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       | node-fetch@3.0.0-beta.10
| node             | v14.17.3
| npm              | 6.14.13
| Operating System | macOS-11.4

**Additional context/Screenshots**
test in repl

![image](https://user-images.githubusercontent.com/243154/128348639-9d6d7df1-6794-4205-916b-92f968a4d7c2.png)

![image](https://user-images.githubusercontent.com/243154/128349067-b0bb8b46-7805-4410-afd3-fc43fe3be16a.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Richienb** [comment] 2021-08-05 12:27
Duplicate of #1226

**Closed** 2021-08-05 12:28 UTC
Labels: question
