### ISSUE TITLE
node-fetch unusable with esm package

### ISSUE THREAD

**Issue by michaelm-rsi** [node-fetch/node-fetch#1299] opened 2021-09-20 16:13 UTC
Given an index.js file with `import fetch from "node-fetch"`
When I run cli command `node -r esm index.js`
Then I should see the script import fetch and run.

```
Version 3 gives this error.
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13) {
 code: 'ERR_REQUIRE_ESM'
}
```

Now, I've read the similar threads on this.  One thing that hasn't been mentioned, that the maintainers overlook, is there are still MAJOR projects out there that can't be used with ESM directly.  Cucumber.js is one of them.  The top level project must be CJS for cucumber to work, but you can convince it to work seemlessly with the ESM package.

**Comment by jimmywarting** [comment] 2021-09-20 16:44
> As popular as this package is, did any of the maintainers bother to test whether these changes would work with it?

We can't possible test each and every "thing" in the wild. I haven't even heard of Cucumber upon till this point. 
It's unreasonable to think that we should test Cucumber, WebPack, rollup, TypeScript, babel, gulp, jest, ts-jest, jest-fetch-mock and everything that is out there. If we make a Major change, then it's up to others to make it work.

**Comment by jimmywarting** [comment] 2021-09-20 16:46
Hi. 

> The top level project must be CJS for cucumber to work

I don't know much about cucumber but they have announced that they have experimental support for esm https://github.com/cucumber/cucumber-js/blob/main/docs/esm.md

Could you take a look in https://github.com/node-fetch/node-fetch/issues/1279 if you find some helpful solution/workaround?

**Comment by pakastin** [comment] 2021-09-20 20:58
Seems unusable here as well 🤨

**Comment by michaelm-rsi** [comment] 2021-09-21 22:08
I'm trying to get up to speed to actually contribute code on the Cucumber project, and ESM support is one of the branches I'm following to get a feel for what needs to be done.  So I'm aware of the ticket and the problem that the Cucumber test library needs the project to be CJS to run correctly unless node is ran using the esm package.

I don't expect any maintainer to test *everything* in the wild, that's why I filed a bug. If you aren't interested in maintaining interoperability with other projects that's your prerogative. 

Honestly, if you're going to do such a break it would be better to follow the path the moment.js team did - they created a new package named luxon.js and marketed moment as bug-fix only.  In a similar manner you could make a new package node-fetch-esm and declare the current branch as entering a bug fix only phase with no new features, also set an end of life for the project around 3 to 5 years out from now.

**Comment by mattkrick** [comment] 2021-09-23 01:06
Would you be open to v2 having feature parity of v3 but compiled down to cjs?
Making the business case to migrate an entire app to ESM is difficult.

I'm OK with sticking the v2, but would love to get typescript typings backported to that version.
`@types/node-fetch` is just a stub at `^3.0.0` and at `2.5.12` it had bad typings for the `AbortController`.

I'm afraid if it's not usuable, it'll just divide the ecosystem, we'll have a handful of packages published like `node-fetch-usable` and one of them is bound to have a security vuln.

**Comment by jimmywarting** [comment] 2021-09-23 10:43
We can't possible bring everything from v3 to v2 as some stuff would be breaking.

**Comment by tenbits** [comment] 2021-09-25 21:47
We were also forced to downgrade to v2 due to this issue. Why you don't consider to build the library to a single file? This would increase the load performance, compatibility and decrease the size of the library.

**Comment by jimmywarting** [comment] 2021-09-26 08:15
> Why you don't consider to build the library to a single file? This would increase the load performance, compatibility and decrease the size of the library.

It's not beneficial, read this thread #1227

**Comment by tenbits** [comment] 2021-09-26 17:01
This is extremely opinioned position, which shouldn't be the case for the lib, as both should be supported, while they **are** and **will be** both first-class module systems. A consumer should be able to use the library disregarding of which module system he/she uses. This is even disrespectful to those, who for any of the reasons use cjs.

**Comment by mattkrick** [comment] 2021-09-29 21:40
> We can't possible bring everything from v3 to v2 as some stuff would be breaking.

I could be wrong, I often am, but if the choice is between a breaking change in a minor version and having 2 unusable versions, i'd vote for breaking semver once.

**Comment by mariusa** [comment] 2021-11-02 10:23
>  In a similar manner you could make a new package node-fetch-esm and declare the current branch as entering a bug fix only phase with no new features, also set an end of life for the project around 3 to 5 years out from now.

That's why we have major versions. Can't create a new package every time something major changes.

> there are still MAJOR projects out there that can't be used with ESM directly

Use node-fetch 2.x then

I just migrated a small project to ESM and happily using node-fetch 3.x. node-fetch is usable with esm. Not sure why this issue was reported / is still open.

**Comment by jimmywarting** [comment] 2021-11-02 10:35
we also have similar cjs/esm issues open that are basically a dupl of this, so closing this one... 
There isn't any issue with node-fetch itself
This (now) ESM-only package works as intended. if you have a problem with using ESM-only packages or any other solution highlighted in #1227 then it's really up to you to fix it


There is  also a discussion about having  a  exposed cjs file that only export fetch (not headers, Response and Request) 
that is related to this: #1327

**Closed by jimmywarting** 2021-11-02 10:35 UTC
