### ISSUE TITLE
ECONNREFUSED on NodeJS 18

### ISSUE THREAD

**Issue by unional** [node-fetch/node-fetch#1624] opened 2022-08-12 06:52 UTC
When using `node-fetch` on NodeJS 18, got ECONNREFUSED

```js
// test.mjs
import { Server } from '@hapi/hapi'
import fetch from 'node-fetch'

const start = async () => {
  const server = new Server({
    port: 3344,
  })

  server.route([
    {
      method: 'GET',
      path: '/',
      handler: async () => {
        return JSON.stringify({ value: 'hello' })
      }
    }
  ])
  await server.start()


  const response = await fetch('http://localhost:3344')
  console.log('response', await response.text())
}

start()
```

1. Run the above in Node 18.7.0. It fails with:

```sh
FetchError: request to http://localhost:3344/ failed, reason: connect ECONNREFUSED ::1:3344
    at ClientRequest.<anonymous> (file:///D:/code/mocktomata/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  erroredSysCall: 'connect'
}
```

**Expected behavior**

The same script will work in NodeJS 16.

Video repro: https://youtu.be/PgyYPw4RCoI

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |  2.6.7, 3.2.10
| node             | 18.7.0
| @hapi/hapi              | 20.2.2
| Operating System | Windows

**Comment by unional** [comment] 2022-08-12 07:15
Calling the server using curl is working, showing it is not a problem of `@hapi/hapi`:

```sh
curl http://localhost:3344 -v
*   Trying 127.0.0.1:3344...
* Connected to localhost (127.0.0.1) port 3344 (#0)
> GET / HTTP/1.1
> Host: localhost:3344
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< cache-control: no-cache
< content-length: 17
< accept-ranges: bytes
< Date: Fri, 12 Aug 2022 07:14:03 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{"value":"hello"}* Connection #0 to host localhost left intact
```

**Comment by tnwanna** [comment] 2022-08-31 21:09
I started seeing this and the only solution I found was to use the IP `127.0.0.1` instead of `localhost`. I'm not sure why

**Comment by LinusU** [comment] 2022-09-02 19:18
> I started seeing this and the only solution I found was to use the IP `127.0.0.1` instead of `localhost`. I'm not sure why

This would be since `localhost` resolves to `::1` which is the "equivalent" of 127.0.0.1 but in IPv6 instead of IPv4. Since the server seems to be listening only on IPv4 this means that the connection will be refused when trying `::1`.

I believe that this error exists when using the builtin `http` module as well, and probably has to do with how Node.js does dns resolving...

If you want to move forward with this I would suggest first seeing if you can reproduce the same issue using the builtin `http` module, and if you can, file an issue with Node.js directly. If this cannot be reproduced in the builtin `http` module, than it is most likely something in this module that messes this up.

**Comment by danielstaleiny** [comment] 2022-09-11 21:05
Can confirm this issue on Node version v18.8.0. I am getting the very same error on different port 8080. Calling with curl works, calling from node results in `ECONNREFUSED` as described above.

I can also confirm that the very same code worked on node 16.X.X. I can also confirm that changing `localhost` to `127.0.0.1` fixes the issue.

**Comment by danielstaleiny** [comment] 2022-10-10 12:09
Indeed it is issue with nodejs. https://github.com/nodejs/node/issues/40702

**Comment by tnwanna** [comment] 2022-10-12 13:15
One thing to check for people seeing this on Macs, specifically with port 5000, is Airplay Receiver. I learned that it actually uses localhost:5000 and it was the reason, at least in my case, that the IP worked, but localhost didn't. I think an update from our IT must've enabled it without me realizing it

**Comment by avivnakar** [comment] 2022-11-15 09:15
I experience the same issue,
I use nvm for Windows and same code works properly for 16.17.0

**Comment by hasanur-rahman079** [comment] 2022-11-26 11:49
> I started seeing this and the only solution I found was to use the IP `127.0.0.1` instead of `localhost`. I'm not sure why

That worked for me!

**Comment by meistens** [comment] 2023-01-14 16:14
> I started seeing this and the only solution I found was to use the IP `127.0.0.1` instead of `localhost`. I'm not sure why

works on node 16 but above solution doesn't work even if the IP were changed to localhost

**Comment by dginzbourg** [comment] 2023-01-29 17:04
there was a breaking change in node v17 that changed the default IP resolving. ip6 is preferred by default. You can add ```dns.setDefaultResultOrder('ipv4first')``` at the beginning of you app and that should fix the problem (https://nodejs.org/api/dns.html#dnssetdefaultresultorderorder)

**Comment by meistens** [comment] 2023-01-30 07:32
> there was a breaking change in node v17 that changed the default IP resolving. ip6 is preferred by default. You can add ```dns.setDefaultResultOrder('ipv4first')``` at the beginning of you app and that should fix the problem (https://nodejs.org/api/dns.html#dnssetdefaultresultorderorder)

This fixed the issue, didn't realize the cause was from Node and going by the error message I got, thought it was something else.

Thanks anyway.

**Comment by LinusU** [comment] 2023-01-30 09:29
At this point it seems like the underlying problem is identified, and that there is nothing that should be changed in `node-fetch`. Happy to re-open if someone disagrees 👍

**Closed by LinusU** 2023-01-30 09:29 UTC
Labels: bug

**Comment by Abdona** [comment] 2023-02-21 12:56
Changing 'localhost' to '127.0.0.1' has fixed the problem for me.

> I started seeing this and the only solution I found was to use the IP `127.0.0.1` instead of `localhost`. I'm not sure why

**Comment by jatoni** [comment] 2023-03-30 00:54
I changed localhost to 127.0.0.1, I don't know what is the reason but work successfully

**Comment by gcacars** [comment] 2023-04-04 19:13
Node.js 18+ has built-in `fetch`. You just need to remove this package.

**Comment by simonmaass** [comment] 2023-10-17 17:12
why was this closed? we are still having this issue when using 'localhost'

**Comment by tahmidrahman-dsi** [comment] 2024-01-17 08:05
Is there anyone having this issue in Ubuntu 20.04.6 with node version 18.19.0?

**Comment by lispercat** [comment] 2024-03-14 22:28
I have the issue with node v18.17.1. Neither setting ip to 127.0.0.1 or dns.setDefaultResultOrder('ipv4first'); fixes the problem.

**Comment by 0xtrou** [comment] 2024-04-18 14:55
I confirmed this fixed the issue

```
require('node:dns').setDefaultResultOrder('ipv4first');
```

**Comment by matthew-b-payne** [comment] 2024-05-01 17:21
On a mac, commenting out the ipv6 entry forces the ipv4 resolution. 
comment out this line as alternative to using 127.0.0.1
e.g. ##::1             localhost

**Comment by jhay06** [comment] 2024-06-14 08:31
> I confirmed this fixed the issue
> 
> ```
> require('node:dns').setDefaultResultOrder('ipv4first');
> ```

this works

**Comment by ayrtoneverton** [comment] 2025-01-19 13:28
Just to try to help someone, I went through something similar and managed to solve it by setting this Env: `NODE_TLS_REJECT_UNAUTHORIZED=0`.

Ref: https://stackoverflow.com/a/21961005/10686489
