### ISSUE TITLE
Bug: Uncaught error: "TypeError [ERR_INVALID_URL]: Invalid URL: https://"

### ISSUE THREAD

**Issue by mikeconley12** [node-fetch/node-fetch#889] opened 2020-06-26 21:43 UTC
Uncaught error: `TypeError [ERR_INVALID_URL]: Invalid URL: https://`

**Reproduction**

See the [PoC](https://repl.it/repls/UnfoldedShockingLocus#index.js)

```javascript
const Koa = require("koa");
const fetch = require("node-fetch");

const app = new Koa();

app.use(async ctx => {
  ctx.set("Location", "https://");
  ctx.status = 301;
});

app.listen(3000);

(async () => {
  try {
    await fetch("http://localhost:3000");
  } catch (error) {
    console.log("catch");
  }
  console.log("done");
})();
```

**Expected behavior**

The PoC should print: 

```
catch
done
```

**Actual behavior**

The PoC prints:

```
internal/url.js:257
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: https://
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at ClientRequest.<anonymous> (/home/runner/UnfoldedShockingLocus/node_modules/node-fetch/dist/index.cjs:1291:52)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:469:22)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12) {
  input: 'https://',
  code: 'ERR_INVALID_URL'
}
```

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0-beta.7
| node             | 12.16.3
| npm              | 6.14.4
| Operating System | Linux

**Comment by JefferyHus** [comment] 2020-06-28 23:48
I am not familiar with `koa`, but what does this part mean? You are trying to force redirection to `https`?

```javascript
app.use(async ctx => {
  ctx.set("Location", "https://");
  ctx.status = 301;
});
```

**Comment by mikeconley12** [comment] 2020-06-29 08:58
Hi @JefferyHus !

```
app.use(async ctx => {
  ctx.set("Location", "https://"); // set Location header
  ctx.status = 301; // set HTTP status code
});
```

The code will return the following HTTP response:

```
HTTP/1.1 301 Moved Permanently
Location: https://
Content-Type: text/plain; charset=utf-8
Content-Length: 17
Date: Mon, 29 Jun 2020 08:53:38 GMT
Connection: keep-alive
```

**Comment by JefferyHus** [comment] 2020-06-29 12:08
So it's a redirection. The error you have comes from that part exactly not `node-fetch`

**Comment by mikeconley12** [comment] 2020-06-29 16:20
> So it's a redirection. The error you have comes from that part exactly not `node-fetch`

No, look at this line in the stack trace:

```
    at ClientRequest.<anonymous> (/home/runner/UnfoldedShockingLocus/node_modules/node-fetch/dist/index.cjs:1291:52)
```

**Comment by JefferyHus** [comment] 2020-06-30 01:41
What happens is that when `node-fetch` requests `http://localhost:3000`, `koa` redirects the request towards `https://` and that's not a correct URL at all.

The issue is not package related, it's normal to throw such an error, it makes more sense to throw that error because the issue is within your code.

Try this and it will fix your problem:

```javascript
const Koa = require("koa");
const fetch = require("node-fetch");

const app = new Koa();

app.use(async ctx => {
  ctx.set("Location", "https://localhost:3000");
  ctx.status = 301;
});

app.listen(3000);

(async () => {
  try {
    await fetch("http://localhost:3000");
  } catch (error) {
    console.log("catch");
  }
  console.log("done");
})();
```

**Comment by mikeconley12** [comment] 2020-06-30 09:03
@JefferyHus 
I am 100% aware that I am redirecting to the invalid URL.
I wrote this HTTP server only to reproduce this bug that I had with another HTTP server.

Did you run the PoC: https://repl.it/repls/UnfoldedShockingLocus#index.js ?

There are two issues:

1. **It's impossible to catch the error in my code. The error stops Node.js process.**

2. The bug is here: https://github.com/node-fetch/node-fetch/blob/0f0e6253ae92c5192b07803e4176df0f4e69f8ff/src/index.js#L108 . If this bug will be fixed as follows:

	```
	let locationURL;
	try {
		locationURL = location === null ? null : new URL(location, request.url);
	} catch (error) {
		reject(error);
		return;
	}
	```

	Then, in the case of the `manual` redirection, the `fetch` promise will be rejected with an error and the HTTP response will be lost.
	My current temporary patch:

	```
	diff --git a/node_modules/node-fetch/dist/index.cjs b/node_modules/node-fetch/dist/index.cjs
	index ff09287..f1cf0ca 100644
	--- a/node_modules/node-fetch/dist/index.cjs
	+++ b/node_modules/node-fetch/dist/index.cjs
	@@ -1288,7 +1288,13 @@ async function fetch(url, options_) {
	 				const location = headers.get('Location');
	 
	 				// HTTP fetch step 5.3
	-				const locationURL = location === null ? null : new URL(location, request.url);
	+				// Patch for https://github.com/node-fetch/node-fetch/issues/889, remove it when the official fix is released
	+				let locationURL;
	+				try {
	+					locationURL = location === null ? null : new URL(location, request.url);
	+				} catch (error) {
	+					locationURL = null;
	+				}
	 
	 				// HTTP fetch step 5.5
	 				switch (request.redirect) {
	```

**Comment by JefferyHus** [comment] 2020-06-30 12:38
Ok, now it makes sense. If you just described it same way in your issue.

**Comment by mikeconley12** [comment] 2020-06-30 12:47
Thanks for validating this issue!

**Comment by luiselullgar23** [comment] 2021-09-04 23:08
Analytics is the key.!

**Comment by jimmywarting** [comment] 2022-01-22 23:17
this have been fixed with a try/catch and `manual` no longer throws for those who wish to manually handle wrong urls in the location header

**Closed by jimmywarting** 2022-01-22 23:17 UTC
Labels: bug

**Comment by douglasg14b** [comment] 2023-03-31 21:40
@jimmywarting In what version...?
